In [2]:
#NumPy 기본: 배열과 벡터 연산
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.54267505, -2.35941261, -0.07308574],
       [ 0.01999737, -0.60157151,  0.20109569]])

In [3]:
data * 10

array([[ -5.42675048, -23.5941261 ,  -0.73085737],
       [  0.19997373,  -6.01571507,   2.01095685]])

In [5]:
data1 = [6, 7.5, 8, 0 ,1]
data1 = np.array(data1)

In [6]:
data1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1, 2, 3, '4'], [1, 2, 3, 4]]
data2 = np.array(data2)
data2

array([['1', '2', '3', '4'],
       ['1', '2', '3', '4']], dtype='<U21')

In [15]:
data2.ndim

2

In [16]:
data2.shape

(2, 4)

In [19]:
data2.dtype

dtype('<U21')

In [21]:
a = 1
a = float(a)
print(a)

1.0


In [24]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [31]:
arr.dtype
arr = arr.astype(np.int32)

In [32]:
print(arr)

[1 2 3 4 5]


In [33]:
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [34]:
arr1 = arr
arr2 = np.array([5, 4, 3, 2, 1])

In [35]:
arr1 + arr2

array([6, 6, 6, 6, 6])

In [36]:
arr1 * arr2

array([5, 8, 9, 8, 5])

In [41]:
arr1 = np.dot([[1, 2], [2, 3], [3, 4]])
arr2 = np.dot([[1, 2, 3, 4], [4, 3, 2, 1]])


TypeError: dot() missing 1 required positional argument: 'b'

In [40]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,2) (2,4) 

In [42]:
arr1 = list(range(10))

In [43]:
arr1_slice = arr1[5:8]

In [44]:
print(arr1_slice)

[5, 6, 7]


In [45]:
arr1_slice[1] = 12345
print(arr1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [46]:
print(arr1_slice)

[5, 12345, 7]


In [47]:
data = np.random

In [48]:
data

<module 'numpy.random' from '/Users/jeonjeung-won/opt/anaconda3/lib/python3.8/site-packages/numpy/random/__init__.py'>

In [49]:
data.randn(7, 4)

array([[-1.44470836, -0.99329449,  0.44455435, -1.23862346],
       [-0.87950813, -0.15220348,  1.17583879,  0.43145215],
       [-1.3334855 ,  0.29046873, -2.41211885, -0.36350869],
       [ 1.16338194,  0.86450826,  0.87081619,  0.55989573],
       [ 0.86273542, -0.68082123, -0.65897198, -2.51602571],
       [-1.1501437 , -0.3218474 ,  0.65182229,  0.50023703],
       [-0.47983382, -1.30857263, -0.33796489, -0.76650894]])

In [62]:
data = np.random.randn(7, 4)
data

array([[-1.31834736, -1.48038317,  0.66293698,  0.23151652],
       [-0.71856886, -1.15525206,  0.14460882,  2.22021352],
       [-0.32898587,  0.00915225, -0.08766841,  0.47694748],
       [-0.69329842, -0.54870554, -1.09043927, -1.18532997],
       [ 0.42174608,  0.48319854,  1.7841234 , -0.02431114],
       [ 0.57477241, -1.64829879,  0.4692003 ,  0.32775452],
       [ 0.72568393,  0.34521259,  1.33849747, -0.35255402]])

In [52]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [53]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [54]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
data[names == 'Bob']

array([[-1.31834736, -1.48038317,  0.66293698,  0.23151652],
       [-0.69329842, -0.54870554, -1.09043927, -1.18532997]])

In [64]:
data[(names == 'Bob' | names == 'Will')]

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [65]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-1.31834736, -1.48038317,  0.66293698,  0.23151652],
       [-0.32898587,  0.00915225, -0.08766841,  0.47694748],
       [-0.69329842, -0.54870554, -1.09043927, -1.18532997],
       [ 0.42174608,  0.48319854,  1.7841234 , -0.02431114]])

In [66]:
data[data < 0] = 0

In [67]:
data

array([[0.        , 0.        , 0.66293698, 0.23151652],
       [0.        , 0.        , 0.14460882, 2.22021352],
       [0.        , 0.00915225, 0.        , 0.47694748],
       [0.        , 0.        , 0.        , 0.        ],
       [0.42174608, 0.48319854, 1.7841234 , 0.        ],
       [0.57477241, 0.        , 0.4692003 , 0.32775452],
       [0.72568393, 0.34521259, 1.33849747, 0.        ]])

In [68]:
data[names != 'Joe'] = 7

In [69]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.14460882, 2.22021352],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.57477241, 0.        , 0.4692003 , 0.32775452],
       [0.72568393, 0.34521259, 1.33849747, 0.        ]])

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [96]:
arr = np.empty((8, 4), dtype=int)
for i in range(8):
    arr[i] = i
arr[1, 2]

1

In [97]:
arr[[1, 2]]

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [104]:
arr = np.arange(32).reshape(8, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [99]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [102]:
arr[[1, 5, 7, 2]][[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [105]:
arr = np.arange(15).reshape(3, 5)
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [106]:
a = np.random.randn(8)
b = np.random.randn(8)
a - b

array([-1.72166939,  0.19936739,  1.99209513, -1.34562616, -1.46001913,
       -1.34413231,  2.14294747, -0.22284405])

In [107]:
abs(a)

array([0.37010765, 1.10000869, 2.07118536, 1.12196492, 0.52161262,
       1.24409893, 1.19560153, 0.09580686])

In [109]:
a
b
abs(a)

array([0.37010765, 1.10000869, 2.07118536, 1.12196492, 0.52161262,
       1.24409893, 1.19560153, 0.09580686])

In [110]:
a

array([-0.37010765, -1.10000869,  2.07118536,  1.12196492, -0.52161262,
       -1.24409893,  1.19560153,  0.09580686])

In [111]:
print(a)
print(b)
abs(a)

[-0.37010765 -1.10000869  2.07118536  1.12196492 -0.52161262 -1.24409893
  1.19560153  0.09580686]
[ 1.35156174 -1.29937608  0.07909023  2.46759109  0.93840651  0.10003338
 -0.94734594  0.31865091]


array([0.37010765, 1.10000869, 2.07118536, 1.12196492, 0.52161262,
       1.24409893, 1.19560153, 0.09580686])

In [112]:
%time a + b

CPU times: user 11 µs, sys: 0 ns, total: 11 µs
Wall time: 13.8 µs


array([ 0.9814541 , -2.39938476,  2.15027559,  3.58955601,  0.41679389,
       -1.14406556,  0.24825558,  0.41445777])

In [113]:
%time np.add(a, b)

CPU times: user 11 µs, sys: 0 ns, total: 11 µs
Wall time: 13.8 µs


array([ 0.9814541 , -2.39938476,  2.15027559,  3.58955601,  0.41679389,
       -1.14406556,  0.24825558,  0.41445777])

In [123]:
a = np.random.randn(1, 2, 3, 4, 5, 6, 7, 8)
b = np.random.randn(1, 2, 3, 4, 5, 6, 7, 8)
%time a + b
%time np.add(a, b)

CPU times: user 103 µs, sys: 72 µs, total: 175 µs
Wall time: 179 µs
CPU times: user 39 µs, sys: 4 µs, total: 43 µs
Wall time: 45.1 µs


array([[[[[[[[-3.55211495e-01,  1.07790066e+00,  2.05128955e-01,
              ...,  1.35572256e+00,  1.68667199e+00,
              -1.69065712e+00],
             [-1.39308073e-02,  1.69467369e+00,  1.97354642e+00,
              ..., -1.45889427e+00, -5.17788969e-01,
               1.41045614e+00],
             [-1.41071441e+00,  1.27526405e+00,  1.34961273e+00,
              ..., -2.72024890e+00,  2.05928011e+00,
              -4.23765550e+00],
             ...,
             [ 1.86344221e-01,  1.78752928e+00,  2.39935197e-01,
              ..., -5.25789912e-01, -7.80081204e-01,
              -7.74141911e-02],
             [-2.06544199e+00, -1.37034001e+00,  1.84698490e-01,
              ...,  7.25894307e-01, -5.21534646e-02,
               3.91773133e+00],
             [-2.00768856e+00, -4.13190371e-01,  8.85130122e-01,
              ...,  1.30684897e+00, -1.20103642e+00,
              -7.32405113e-01]],

            [[-7.27961045e-01, -5.47069969e-01,  9.27884091e-02,
              .

In [127]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
z = np.sqrt(xs ** 2 + ys ** 2)

In [129]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [130]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [131]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [134]:
arr = np.random.randn(4, 4)

In [136]:
arr[arr > 0] = 2

In [137]:
arr

array([[ 2.        , -1.10223503, -0.73091148, -0.99159663],
       [-1.61368143,  2.        , -0.59861968,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.37953155,  2.        , -0.06271264]])

In [3]:
import numpy as np
arr = np.random.randn(100)
print(arr > 0)

[ True  True False False False  True  True False  True False  True False
 False  True  True  True  True  True  True False False  True False  True
 False  True False False False False  True False  True False False  True
  True False False  True  True False False  True  True  True False  True
 False False False  True  True False False  True  True  True False False
 False False  True False  True False  True  True False  True  True False
 False False False False  True  True False False  True False  True  True
  True  True False False  True  True  True  True False False  True  True
 False  True False False]
