In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2[['a', 'b']]

a   -5
b    7
dtype: int64

In [12]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [13]:
sdata = {'ohio' : 35000, 'texas' : 71000, 'oregon' : 16000, 'utah' : 5000}

In [14]:
obj3 = pd.Series(sdata)

In [15]:
obj3

ohio      35000
texas     71000
oregon    16000
utah       5000
dtype: int64

In [16]:
states = ['california', 'ohio', 'oregon', 'texas']

In [17]:
obj4 = pd.Series(sdata, index=states)

In [18]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [19]:
obj4.name = 'population'

In [20]:
obj4.index.name = 'state'

In [21]:
obj4

state
california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
Name: population, dtype: float64

In [22]:
sdata2 = {'wonju' : 30, 'seoul' : 1000, 'jeju' : 50, 'busan' : 500}

In [23]:
obj5 = pd.Series(sdata2)

In [24]:
obj5

wonju      30
seoul    1000
jeju       50
busan     500
dtype: int64

In [25]:
obj5['wonju'] = 35

In [26]:
obj5

wonju      35
seoul    1000
jeju       50
busan     500
dtype: int64

In [27]:
states = ['wonju', 'seoul', 'busan', 'suwon']

In [28]:
obj6 = pd.Series(sdata2, states)

In [29]:
pd.isnull(obj6)

wonju    False
seoul    False
busan    False
suwon     True
dtype: bool

In [30]:
obj6

wonju      30.0
seoul    1000.0
busan     500.0
suwon       NaN
dtype: float64

In [31]:
obj5 + obj6

busan    1000.0
jeju        NaN
seoul    2000.0
suwon       NaN
wonju      65.0
dtype: float64

In [32]:
obj5.name = 'population'

In [33]:
obj5.index.name = 'state'

In [34]:
obj5

state
wonju      35
seoul    1000
jeju       50
busan     500
Name: population, dtype: int64

In [36]:
obj5[['wonju', 'seoul']]

state
wonju      35
seoul    1000
Name: population, dtype: int64

In [37]:
data = {'state': ['ohio', 'ohio', 'ohio', 'nevada', 'nevada', 'nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  nevada  2003  3.2

In [39]:
data

{'state': ['ohio', 'ohio', 'ohio', 'nevada', 'nevada', 'nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [42]:
frame.head()

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [41]:
pd.head(frame)

AttributeError: module 'pandas' has no attribute 'head'

In [43]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9
5  2003  nevada  3.2

In [44]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [45]:
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  nevada  2.4  NaN
five   2002  nevada  2.9  NaN
six    2003  nevada  3.2  NaN

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [50]:
frame2.state

one        ohio
two        ohio
three      ohio
four     nevada
five     nevada
six      nevada
Name: state, dtype: object

In [51]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     nevada
five     nevada
six      nevada
Name: state, dtype: object

In [53]:
frame2[['state', 'year']]

state  year
one      ohio  2000
two      ohio  2001
three    ohio  2002
four   nevada  2001
five   nevada  2002
six    nevada  2003

In [54]:
frame2.loc['three']

year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
frame2['debt'] = 1.6

In [59]:
frame2
import numpy as np

In [60]:
frame2['debt'] = np.arange(6.)

In [61]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   0.0
two    2001    ohio  1.7   1.0
three  2002    ohio  3.6   2.0
four   2001  nevada  2.4   3.0
five   2002  nevada  2.9   4.0
six    2003  nevada  3.2   5.0

In [62]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [63]:
frame2['debt'] = val

In [64]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [66]:
frame2['eastern'] = frame2.state == 'ohio'

In [67]:
frame2

year   state  pop  debt  eastern
one    2000    ohio  1.5   NaN     True
two    2001    ohio  1.7  -1.2     True
three  2002    ohio  3.6   NaN     True
four   2001  nevada  2.4  -1.5    False
five   2002  nevada  2.9  -1.7    False
six    2003  nevada  3.2   NaN    False

In [68]:
del frame2['eastern']

In [69]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [70]:
pop = {'nevada': {2001: 2.4, 2002: 2.9},
      'ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [71]:
frame3 = pd.DataFrame(pop)

In [73]:
frame3.T

2001  2002  2000
nevada   2.4   2.9   NaN
ohio     1.7   3.6   1.5

In [74]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [75]:
frame3

state  nevada  ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [76]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [78]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [79]:
index = obj.index

In [80]:
index

Index(['a', 'b', 'c'], dtype='object')

In [81]:
index[1:]

Index(['b', 'c'], dtype='object')

In [83]:
obj

a    0
b    1
c    2
dtype: int64

In [84]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [85]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [86]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [87]:
obj2.index is labels

True

In [2]:
import pandas as pd
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [3]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [4]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [5]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [6]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [18]:
obj3.reindex(range(10), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
6    yellow
7    yellow
8    yellow
9    yellow
dtype: object

In [11]:
range(5)

range(0, 5)


In [10]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['ohio', 'texas', 'california'])

In [38]:
frame

ohio  texas  california
a     0      1           2
c     3      4           5
d     6      7           8

In [21]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [22]:
frame2

ohio  texas  california
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [45]:
states = ['texas', 'california']

In [30]:
frame.reindex(columns=states)
frame.loc['a']

ohio          0
texas         1
california    2
Name: a, dtype: int64

In [46]:

frame.loc[['a', 'c', 'd'], states]

texas  california
a      1           2
c      4           5
d      7           8

In [42]:
from pandas import Series, DataFrame

In [47]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])

In [48]:
new_obj = obj.drop('c')

In [49]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [50]:
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [51]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['ohio', 'colorado', 'utah', 'new york'], columns=['one', 'two', 'three', 'four'])

In [52]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [53]:
data.drop('utah')

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york   12   13     14    15

In [55]:
data.drop('two', axis='columns')

one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
new york   12     14    15

In [56]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [57]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int64

In [58]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [59]:
obj.drop('c', inplace=True)

In [60]:
obj

a    0
b    1
d    3
e    4
dtype: int64